"""Suppression des colonnes historiques de reponse_etudiant

Revision ID: 0587ef34f6ac
Revises: 26135fbcef70
Create Date: 2025-03-25 22:10:48.410867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0587ef34f6ac'
down_revision = '26135fbcef70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse_etudiant', schema=None) as batch_op:
        batch_op.drop_constraint('reponse_etudiant_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('reponse_etudiant_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('reponse_etudiant_ibfk_6', type_='foreignkey')
        batch_op.drop_constraint('reponse_etudiant_ibfk_4', type_='foreignkey')
        batch_op.drop_column('groupe_id')
        batch_op.drop_column('site_id')
        batch_op.drop_column('promotion_id')
        batch_op.drop_column('semestre_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse_etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestre_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('promotion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('site_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('groupe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('reponse_etudiant_ibfk_4', 'groupe', ['groupe_id'], ['id'])
        batch_op.create_foreign_key('reponse_etudiant_ibfk_6', 'site', ['site_id'], ['id'])
        batch_op.create_foreign_key('reponse_etudiant_ibfk_3', 'semestre', ['semestre_id'], ['id'])
        batch_op.create_foreign_key('reponse_etudiant_ibfk_5', 'promotion', ['promotion_id'], ['id'])

    # ### end Alembic commands ###
