"""Ajout de tableaux reponsejuste

Revision ID: 2858260bdaad
Revises: 7e839ee652ee
Create Date: 2025-03-23 12:37:31.399316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2858260bdaad'
down_revision = '7e839ee652ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reponses_justes',
    sa.Column('id_reponse_juste', sa.Integer(), nullable=False),
    sa.Column('numero_question', sa.Integer(), nullable=False),
    sa.Column('choix', sa.String(length=1), nullable=False),
    sa.Column('id_test', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_test'], ['tests.id_test'], ),
    sa.PrimaryKeyConstraint('id_reponse_juste')
    )
    op.drop_table('groupes')
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_index('uq_email')

    op.drop_table('etudiant')
    op.drop_table('user')
    op.drop_table('tests_groupes')
    op.drop_table('evaluation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('questions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('penalite', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('classe', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tests_groupes',
    sa.Column('id_test', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_groupe', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('titre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('nombre_evaluation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nombre_etudiant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_groupe'], ['groupes.id_groupe'], name='tests_groupes_ibfk_1'),
    sa.PrimaryKeyConstraint('id_test'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('etudiant',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('promotion', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('groupe', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('site', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('specialite', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.create_index('uq_email', ['email'], unique=True)

    op.create_table('groupes',
    sa.Column('id_groupe', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_promotion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_groupe'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('reponses_justes')
    # ### end Alembic commands ###
