"""Ajout de score reponseProf reponsEtud

Revision ID: 8528fd85b830
Revises: d3885d7cf680
Create Date: 2025-03-17 17:48:58.251465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8528fd85b830'
down_revision = 'd3885d7cf680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reponse_prof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_question', sa.String(length=50), nullable=False),
    sa.Column('choix', sa.String(length=2), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reponse_etudiant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_question', sa.String(length=50), nullable=False),
    sa.Column('choix', sa.String(length=2), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiant.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_total', sa.Float(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiant.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('reponse_etudiant')
    op.drop_table('reponse_prof')
    # ### end Alembic commands ###
