"""Ajout des tables Teacher et Prof

Revision ID: be8132f0a4de
Revises: 
Create Date: 2025-03-31 19:07:37.383482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8132f0a4de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tests',
    sa.Column('id_test', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_test')
    )
    op.create_table('reponses_justes',
    sa.Column('id_reponse_juste', sa.Integer(), nullable=False),
    sa.Column('numero_question', sa.Integer(), nullable=False),
    sa.Column('choix', sa.String(length=1), nullable=False),
    sa.Column('id_test', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_test'], ['tests.id_test'], ),
    sa.PrimaryKeyConstraint('id_reponse_juste')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reponses_justes')
    op.drop_table('tests')
    op.drop_table('prof')
    # ### end Alembic commands ###
