"""ajout annee

Revision ID: cd3c8571b083
Revises: ddbb3c9d52b3
Create Date: 2025-01-27 21:32:05.405449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3c8571b083'
down_revision = 'ddbb3c9d52b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_column('annee')

    # ### end Alembic commands ###
