"""ajout des tables

Revision ID: ddbb3c9d52b3
Revises: adee241195f8
Create Date: 2025-01-27 21:26:14.332879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbb3c9d52b3'
down_revision = 'adee241195f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etudiant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('promotion', sa.String(length=50), nullable=False),
    sa.Column('groupe', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etudiant')
    # ### end Alembic commands ###
