"""Ajout des champs

Revision ID: e61e10d2a169
Revises: 8528fd85b830
Create Date: 2025-03-17 20:00:04.097455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e61e10d2a169'
down_revision = '8528fd85b830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('h2_oral', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('note_oral', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('score_oral', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('h2_ecrit', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('note_ecrit', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('score_ecrit', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('score_total_toeic', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('note_cc', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('note_ecue_toeic', sa.Float(), nullable=False))
        batch_op.drop_column('note_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_total', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('note_ecue_toeic')
        batch_op.drop_column('note_cc')
        batch_op.drop_column('score_total_toeic')
        batch_op.drop_column('score_ecrit')
        batch_op.drop_column('note_ecrit')
        batch_op.drop_column('h2_ecrit')
        batch_op.drop_column('score_oral')
        batch_op.drop_column('note_oral')
        batch_op.drop_column('h2_oral')

    # ### end Alembic commands ###
