"""Description des modifications

Revision ID: 26135fbcef70
Revises: 62dc4ed91db6
Create Date: 2025-03-22 23:18:55.145410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26135fbcef70'
down_revision = '62dc4ed91db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groupe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestre_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'semestre', ['semestre_id'], ['id'])

    with op.batch_alter_table('reponse_etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('promotion_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('semestre_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('groupe_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'semestre', ['semestre_id'], ['id'])
        batch_op.create_foreign_key(None, 'groupe', ['groupe_id'], ['id'])
        batch_op.create_foreign_key(None, 'promotion', ['promotion_id'], ['id'])
        batch_op.create_foreign_key(None, 'site', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse_etudiant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('groupe_id')
        batch_op.drop_column('semestre_id')
        batch_op.drop_column('promotion_id')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('groupe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semestre_id')

    # ### end Alembic commands ###
