"""Suppression de la colonne annee

Revision ID: 2c0ec2364d2e
Revises: cd3c8571b083
Create Date: 2025-01-28 18:39:16.668478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c0ec2364d2e'
down_revision = 'cd3c8571b083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_column('annee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
